name: Python Pull Request Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install dependencies via Poetry
        run: poetry install

      - name: Run tests
        run: poetry run python manage.py test
        env:
            DJANGO_ALLOWED_HOSTS: 'localhost 127.0.0.1'

      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
